version: '3.8'

services:

  Overseer_FE:
    hostname: Overseer_FE
    container_name: Overseer_FE
    image: overseer_fe:latest
    build:
      context: ./docker/docker-apache
      dockerfile: apache.dockerfile
    env_file: ./docker/docker-apache/apache.env
    volumes:
      - ./frontend:/var/www/html
    expose:
      - '80'
      - '8080'
      - '443'
    tty: true
    stdin_open: true
    network_mode: "host"
    extra_hosts:
      - "Overseer_FE:127.0.1.1"
      - "overseer.home:${HOST_IP:-127.0.0.1}"