services:

  Overseer:
    hostname: Overseer
    container_name: Overseer
    image: overseer:latest
    build:
      context: ./docker
      dockerfile: docker-overseer/overseer.dockerfile
    env_file:
      - ./.env
    environment:
      - OSN_HOST=${OSN_HOST}
      - OSN_PORT=${OSN_PORT}
      - PING_INT=${PING_INT}
      - PING_TMT=${PING_TMT}
    volumes:
      - ./volumes/overseer:/Overseer:ro
      - ./docker/docker-apache/web/private/certs/root:/certs/root:ro
      - ./docker/docker-apache/web/private/certs/overseer:/certs/overseer:ro
    expose:
      - "${OSN_PORT}"
    ports:
      - "${OSN_PORT}:${OSN_PORT}"
    tty: true
    stdin_open: true
    networks:
      - OSN

  Overseer_FE:
    hostname: Overseer_FE
    container_name: Overseer_FE
    image: overseer_fe:latest
    build:
      context: ./docker
      dockerfile: docker-apache/apache.dockerfile
    env_file:
      - ./.env
      - ./docker/docker-apache/apache.env 
      - ./docker/docker-mysql/mysql.env
    volumes:
      - ./volumes/frontend/public:/var/www/html:ro
      - ./volumes/frontend/private:/private:ro
      - ./volumes/frontend/firmware:/var/www/overseer/firmware
      - ./docker/docker-apache/web/private/certs/root:/certs/root:ro
      - ./docker/docker-apache/web/private/certs/apache:/certs/apache:ro
    ports:
      - "80:80"
      - "443:443"
    tty: true
    stdin_open: true
    networks:
      - OSN
    extra_hosts:
      - "Overseer_FE:127.0.1.1"
      - "overseer.home:${HOST_IP:-127.0.0.1}"
    command: >
      sh -c "chown -R www-data:www-data /var/www/overseer/firmware && apache2-foreground"


  Overseer_DB:
    hostname: Overseer_DB
    container_name: Overseer_DB
    image: overseer_db:latest
    build:
      context: ./docker
      dockerfile: docker-mysql/mysql.dockerfile
    env_file:
      - ./.env
      - ./docker/docker-mysql/mysql.env
    volumes:
      - ./volumes/database/db:/var/lib/mysql
      - ./volumes/database/config/Overseer.cnf:/etc/mysql/conf.d/mariadb.cnf:ro
      - ./volumes/database/sql/:/docker-entrypoint-initdb.d/:ro
      - ./docker/docker-apache/web/private/certs/root:/certs/root:ro
      - ./docker/docker-apache/web/private/certs/mysql:/certs/mysql:ro
    tty: true
    stdin_open: true
    networks:
      - OSN

networks:
  OSN:
    name: OSN
    driver: bridge